wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701442357.310515
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      3:
      - 23
      4: 3.10.9
      5: 0.15.12
      6: 4.24.0
      8:
      - 5
      13: linux-x86_64
dataset:
  desc: null
  value: ../DEMO/capella-oem/
seed:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 16
n_epochs:
  desc: null
  value: 100
test_mode:
  desc: null
  value: false
train_city:
  desc: null
  value: all
img_factor:
  desc: null
  value: 0.25
large_test:
  desc: null
  value: null
wandb:
  desc: null
  value: true
label_ver:
  desc: null
  value: 1
log_plt:
  desc: null
  value: true
log_fig:
  desc: null
  value: true
outdir:
  desc: null
  value: results/1202
rotate:
  desc: null
  value: 0
use_pe:
  desc: null
  value: true
